FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# launch
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app c1297303b7a1
# docker-compose up
